### ISSUE TITLE
[ROADMAP] Sprint1

### ISSUE THREAD

**Issue by lkorczowski** [lkorczowski/Tinnitus-n-Sleep#1]
- [x] make notebook work on both end
- [ ] implement simple threshold burst detection (2 times the amplitude)
- [ ] implement burst tagging (up to 2sec) and bruxisme tagging (more than 2sec)
- [x] learn to do PR (@RobinGuillard ), see https://github.com/lkorczowski/Tinnitus-n-Sleep/issues/1#issuecomment-603113985
- [x] clean the code and PR (@lkorczowski ) and review changes (@RobinGuillard )
- [x] set continuous integration with GitHub Actions (@lkorczowski )
- [x] update git / github documentation (@lkorczowski )
- [x] add git workflow (branchs, projects, dev, features, bug, etc.) "HOWTO CONTRIBUTE"
- [x] review #4 (@RobinGuillard )
- [x] review #5 (@RobinGuillard )
- [ ] add a signal quality check on epochs refering to their impedance values (@RobinGuillard )
- [ ] add a function testing electrode disconnection (@lkorczowski )

**Comment by lkorczowski** [comment]
@RobinGuillard : this issue is far from being done ! Reopening :)

**Comment by lkorczowski** [comment]
last two item where postponed to #16
