### ISSUE TITLE
Sprint 10 laterality & etiology comparison

### ISSUE THREAD

**Issue by lkorczowski** [lkorczowski/Tinnitus-n-Sleep#100]
Focus on different ways to analyse MEMA data:
- [ ] Analyze data the same way we did before on overnight tinnitus modulation but with the ear where tinnitus is more important (not only right ears)
- [ ] Same analyses on overnight tinnitus modulation but with Pure MEMA instead of all MEMA.
- [ ] Same analyses on overnight tinnitus modulation but with Bruxism
- [ ] Conduct a Spearman/regression test between laterality of tinnitus and difference of nb of MEMA episodes between ears (important to verify a priori if sensors not lost during the night)
- [ ] Compare MEMA metrics between groups separated by on etiology criteria 
```
Séparation sur les causes d’apparition :
Patients qui ont eu des otites enfants, qui ont eu un trauma sonore, une intervention chirurgicale au niveau de l’OM, ou un trauma crânien   VS le reste
Otite VS le reste ?
Métriques précises à tester entre les groupes :
1)	Oreille bouchée
2)	Otalgie
3)	Hyperacousie
4)	Craquement mâchoire 3-4 fois par semaine 
5)	Douleur muscle de la mastication ou de la face
6)	Modulation somato-sensorielle si >3
7)	Augmentation des acous suite aux siestes
8)	Ronflements (ou apnées sans ronflements)
```

**Comment by lkorczowski** [comment]
#101 has been merged because we split the scope of the PR until we dealt with channel+laterality

Remaining :
- [ ] synthesis of etiology from batch2_data/Etiologie patients inclus anonym.xlsx` to `data_info.csv`(automated or manual ?)

```
Séparation sur les causes d’apparition :
Patients qui ont eu des otites enfants, qui ont eu un trauma sonore, une intervention chirurgicale au niveau de l’OM, ou un trauma crânien   VS le reste
Otite VS le reste ? (pour ça 1SL21, 1UC22 et 1HB20 ont eu des otites enfants)
Métriques précises à tester entre les groupes :
1)	Oreille bouchée
Colonne CD de l'excel, champ "avezvousunsentimentdoreil", avec une réponse "oui" (tout le temps, fréquemment, parfois). Attention, pour certains patients (1DA15, 1DL12, 1MA16, 1SA14) on n'a pas cette info!
1SL21 et 1UC22 concernés, pas forcément 1HB20.
2)	Otalgie
Colonne CI de l'excel, champ "avezvousdesdouleursdansou", avec une réponse "oui" (tout le temps, fréquemment, parfois). 
Attention, manque 1SA14
1UC22, 1SL21, 1HB20 non concernés
3)	Hyperacousie
Colonne BS ou colonne BU = "Oui", (champs "estcequelexpositiondesson" ou "estcequedenombreuxbruitsd")
1UC22 concerné, 1SL21 un petit peu concerné, on ne sait pas exactement pour 1HB20
4)	Craquement mâchoire 3-4 fois par semaine 
Colonne BZ de l'excel, champ "estcequelarticulationdevo", avec une réponse "oui" (tout le temps, fréquemment, parfois).
Patient 1SL21 concerné, pas évident pour les 2 autres
Attention, manque 1SA14 
5)	Douleur ou fatigue muscle de la mastication ou de la face
Colonne BX ou BY de l'excel, champ "ressentezvousdesdouleursa" ou "ressentezvousdelafatiguea", avec une réponse "oui" (tout le temps, fréquemment, parfois). 
Patient 1SL21 concerné, pas évident pour les 2 autres
Attention, manque 1SA14
6)	Modulation somato-sensorielle si >3
Somme des valeurs colonnes DF à DP, test si résultat supérieur à 3. ATTENTION : colonne DQ correspond à "NON" du coup ne pas la compter. 
Attention, manque 1SA14
Oui pour 1UC22, faux pour les 2 autres
7)	Augmentation des acous suite aux siestes
Colonne BN, champ "ressentezvousunehaussedev", réponse : "Oui je ressens une hausse franche de mon acouphène suite aux siestes" UNIQUEMENT 
Oui pour 1HB20, 1SL21 et 1UC22
8)	Ronflements (ou apnées sans ronflements)
Colonne EI, champ "estcequevousronflez", réponse : "Oui"
Attention, pour certains patients (1DA15, 1DL12, 1MA16, 1SA14) on n'a pas cette info!
Oui pour 1HB20, 1SL21 et 1UC22
```

**Comment by lkorczowski** [comment]
> > Séparation sur les causes d’apparition :
> Patients qui ont eu des otites enfants, qui ont eu un trauma sonore, une intervention chirurgicale au niveau de l’OM, ou un trauma crânien   VS le reste
> Otite VS le reste ? (pour ça 1SL21, 1UC22 et 1HB20 ont eu des otites enfants)
> Métriques précises à tester entre les groupes :
> 1)	Oreille bouchée
> Colonne CD de l'excel, champ "avezvousunsentimentdoreil", avec une réponse "oui" (tout le temps, fréquemment, parfois). Attention, pour certains patients (1DA15, 1DL12, 1MA16, 1SA14) on n'a pas cette info!
> 1SL21 et 1UC22 concernés, pas forcément 1HB20.

@RobinGuillard 
Tu es sûr de toi ? Dans leur questionnaires, ils ne notent aucune douleur https://docs.google.com/spreadsheets/d/1GUYdJVfqSiF5PvdqXhqBs7j_O9P7vKwM/
ajouté 

1HB20 : Non, jamais ou presque
1SL21 : Oui, parfois
1UC22 : Oui, fréquemment

> 2)	Otalgie
> Colonne CI de l'excel, champ "avezvousdesdouleursdansou", avec une réponse "oui" (tout le temps, fréquemment, parfois). 
> Attention, manque 1SA14
> 1UC22, 1SL21, 1HB20 non concernés

ajouté **Non, jamais ou presque** pour les trois


> 3)	Hyperacousie
> Colonne BS ou colonne BU = "Oui", (champs "estcequelexpositiondesson" ou "estcequedenombreuxbruitsd")
> 1UC22 concerné, 1SL21 un petit peu concerné, on ne sait pas exactement pour 1HB20

**Non** pour les trois

> 4)	Craquement mâchoire 3-4 fois par semaine 
> Colonne BZ de l'excel, champ "estcequelarticulationdevo", avec une réponse "oui" (tout le temps, fréquemment, parfois).
> Patient 1SL21 concerné, pas évident pour les 2 autres
> Attention, manque 1SA14 

1HB20 : Non, jamais ou presque
1SL21 : Oui, parfois
1UC22 : Non, jamais ou presque

> 5)	Douleur ou fatigue muscle de la mastication ou de la face
> Colonne BX ou BY de l'excel, champ "ressentezvousdesdouleursa" ou "ressentezvousdelafatiguea", avec une réponse "oui" (tout le temps, fréquemment, parfois). 
> Patient 1SL21 concerné, pas évident pour les 2 autres
> Attention, manque 1SA14

1HB20 : Non, jamais ou presque
1SL21 : Oui, fréquemment
1UC22 : Non, jamais ou presque

> 6)	Modulation somato-sensorielle si >3
> Somme des valeurs colonnes DF à DP, test si résultat supérieur à 3. ATTENTION : colonne DQ correspond à "NON" du coup ne pas la compter. 
> Attention, manque 1SA14
> Oui pour 1UC22, faux pour les 2 autres

@RobinGuillard tu es sur ? UC22 a mis 0/10 sur la machoire
j'ai laissé vide pour l'instant

> 7)	Augmentation des acous suite aux siestes
> Colonne BN, champ "ressentezvousunehaussedev", réponse : "Oui je ressens une hausse franche de mon acouphène suite aux siestes" UNIQUEMENT 
> Oui pour 1HB20, 1SL21 et 1UC22

**Oui je ressens une hausse franche de mon acouphène suite aux siestes** ajouté pour les 3

> 8)	Ronflements (ou apnées sans ronflements)
> Colonne EI, champ "estcequevousronflez", réponse : "Oui"
> Attention, pour certains patients (1DA15, 1DL12, 1MA16, 1SA14) on n'a pas cette info!
> Oui pour 1HB20, 1SL21 et 1UC22

**Oui** ajouté pour les 3
