### ISSUE TITLE
Sprint 2

### ISSUE THREAD

**Issue by RobinGuillard** [lkorczowski/Tinnitus-n-Sleep#16]
Milestone to reach: 0.0.2

### Electrode disconnection
- [ ] Identifier et retirer de l'analyse les moments où une électrode est détachée, càd:
- [x] en s'appuyant sur les valeurs d'impédances (@RobinGuillard )
- [ ] en utilisant un algo de détection de décrochement (@lkorczowski)
- [ ] assurer le bon fonctionnement en multi-électrodes

### Bruxism event classification 
- [x] Génération d'une liste de détection d'épisodes de bruxisme à partir d'une liste de bursts (@RobinGuillard)
- [x] Différentiation entre types d'épisodes (toniques, phasiques, mixtes) (@RobinGuillard)
- [x] Bien gérer la gestion en multi-électrodes

### Build automatic reporting for classification algorithm comparison
- [ ] see tasks in #17 

### Build automatic reporting for clinical bruxism assessment
- [x] generate the number of episodes per hour
- [x] generate the number of tonic episodes per hour
- [x] generate the number of phasic episodes per hour
- [x] generate the number of mixed episodes per hour
- [x] generate the number of bursts per hour
- [x] generate the number of episodes per night
- [x] generate the number of bursts per episodes
- [x] total duration of episodes
- [x] mean duration of tonic, phasic and mixed episodes

NOTES: 
- Je vais par ailleurs essayer de prendre contact avec qqun qui saura nous scorer certaines de nos nuits. D. Léger va nous mettre en contact avec Lavigne cette semaine a priori!
Next step: gérer les events d'oreille moyenne!

**Comment by lkorczowski** [comment]
Note that if use in multidimensional context, the very simple rule of for ``AmplitudeThresholding`` allows to discard independent event happening on a single electrode:
https://github.com/lkorczowski/Tinnitus-n-Sleep/blob/6f71ce59a3a91986ee881b5726d536b491735241/tinnsleep/classification.py#L69-L78

Therefore, I believe the most urgent element of this sprint should be proper validation of the methods we develop. To do so, I propose:

### Build automatic reporting for classification algorithm comparison
- [ ] build script to applied our methods to all data
- [ ] automatically export insights and build a report, e.g. : 
- [ ] a. (unsupervised) visualization of N bruxism detected events for visual inspection (assessing false positive), N being low enough to be easy to assess manually and high enough to be statistically valid. This method should be dropped as soon as we have .c
- [ ] b. (unsupervised) temporal distribution of the events (this metric will be used for subsequent sleep state analysis)
- [ ] c. (supervised) AUC score and other metrics (but we need tagging)

After that, any additional method (e.g. electrode disconnection) should be benchmarked using this report. It will save us time and sanity.

**Comment by lkorczowski** [comment]
not sure it is completely done

**Comment by lkorczowski** [comment]
Electrode disconnection added to Sprint 3 #28
