### ISSUE TITLE
Build automatic reporting for classification algorithm comparison

### ISSUE THREAD

**Issue by lkorczowski** [lkorczowski/Tinnitus-n-Sleep#17]
### Build automatic reporting for classification algorithm comparison
- [x] first and foremost: have a proper and clean bruxism_detection notebook ! see #19 
- [x] build script to applied our methods to all data (the notebook should include the output) see #22 
- [ ] automatically export insights and build a report, e.g. : 
- [ ] ~~a. (unsupervised) visualization of N bruxism detected events for visual inspection (assessing false positive), N being low enough to be easy to assess manually and high enough to be statistically valid. This method should be dropped as soon as we have .c~~ @RobinGuillard will do that during Sprint 3 #28 
- [x] b. (unsupervised) temporal distribution of the events (this metric will be used for subsequent sleep state analysis), see #22 
- [ ] ~~c. (supervised) AUC score and other metrics (but we need tagging)~~ discussed in #26 

After that, any additional method (e.g. electrode disconnection) should be benchmarked using this report. It will save us time and sanity.

Discussed but not in the scope of this issue:
- problem when person is awake, see #24 

_Originally posted by @lkorczowski in https://github.com/lkorczowski/Tinnitus-n-Sleep/issues/16#issuecomment-605898163_

**Comment by lkorczowski** [comment]
not sure it is done yert

**Comment by lkorczowski** [comment]
@RobinGuillard : I think should put your remarks here on the metrics we need for the report (and also the caveat of detecting awake)

**Comment by lkorczowski** [comment]
Closing as this issue is split with
- automatic benchmarking #26 
- NB-related tasks in SPRINT 3 #28
