### ISSUE TITLE
Sprint 3

### ISSUE THREAD

**Issue by lkorczowski** [lkorczowski/Tinnitus-n-Sleep#28]
# SPRINT 3
Check project board https://github.com/lkorczowski/Tinnitus-n-Sleep/projects/1

## NB report
- [ ] having a clean NB with integrated code  @RobinGuillard 
- [ ] showing results nicely at each step @RobinGuillard 

## Disconnection algorithm
- [x] get the algorithm working, see #27 @lkorczowski 
- [ ] getting algorithm performance, see #26  @lkorczowski 
- [ ] integration with impedance algorithm @lkorczowski 

## Data 
- [x] extracting of EVA data @RobinGuillard 
- [ ] compare masking volume data with episodes @RobinGuillard 
- [ ] compare EVA data with episodes @RobinGuillard 
- [ ] find good strategy for inter-subject variability management (discussion in #29 )

## Backlog (not urgent, only if SPRINT 3 is doing well)
- [ ] get labeled bruxism data from expert @RobinGuillard 
- [ ] #21 
- [ ] #24 
- [ ] #25 
- [ ] #26 
- [ ] #30 
- [ ] #31

**Comment by lkorczowski** [comment]
added #29, #30 , #31 to backlog

**Comment by lkorczowski** [comment]
Split #17 into #26 (benchmarking) and "clean NB" task

**Comment by lkorczowski** [comment]
Sprint closes even not finished
Sprint 4 #33 starts
