### ISSUE TITLE
Sprint 4

### ISSUE THREAD

**Issue by lkorczowski** [lkorczowski/Tinnitus-n-Sleep#33]
- [x] Get the impedance check annotation result (@RobinGuillard )
- [x] Annotated Recording with all BAD EPOCH from {impedance + is_good}, see #36 
```
input:
impedance
emg

output:
figure with annotated EMG
```
- [x] merge annotation {impedence + is_good} with OR, see #36 
- [x] remove BAD epochs and bad electrodes before AmplideThresholding with check_RMS()
- [x] check_RMS()
- [x] AmplitudeThresholding()
- [x] fuse_with_classif_result()
- [x] plotAnnotation() visualize only burst
- [x] convert burst to episode (@RobinGuillard )
- [x] convert to Annotations (intra) @lkorczowski 
- [x] plotAnnotation for each type of episode (intra) @lkorczowski 
- [x] Generate and print clinical report (@RobinGuillard )

End of sprint Friday 24th of April at 14:00

## Backlog
- [ ] get labeled bruxism data from expert @RobinGuillard 
- [ ] compare masking volume data with episodes @RobinGuillard 
- [ ] compare EVA data with episodes @RobinGuillard 
- [ ] #21 
- [ ] #24 
- [ ] #25 
- [ ] #26 
- [ ] find good strategy for inter-subject variability management (discussion in #29 )
- [ ] #30 
- [ ] #31 
- [ ] #37 Unconsistent number of epoch. see issue for investigation protocol
- [x] #40 wont fix until we see a problem with real data
- [x] #42 wont fix because bad channels will be removed manually when needed

**Comment by lkorczowski** [comment]
ended, start SPRINT 5 #44
