### ISSUE TITLE
Sprint 5

### ISSUE THREAD

**Issue by lkorczowski** [lkorczowski/Tinnitus-n-Sleep#44]
# SPRINT 5

## Bruxism:
- [x] PR #43 (add image) 
- [x] PR #38 
- [x] redone entirely reporting with adaptation (1min, 240 epochs) (see issue #45 )

## Middle Ear(th): detect events and remove artifacts
_signal is a linear mixture of pulse, respiration and middle ear activation. 80% of activation should occur in REM in healthy subjects (10-15% before REM, only 5-10% outside)_
### 3 events:
- activation tensor tympani, 1 positive sharp activation + transient to baseline (0,75 s) with negative (optional)
- activation stapedien, 1 sharp negative flat step + transient to baseline (1-1.5 s)
- activation spamodic, repetition of tensor tympani activation  (min 2 tensors tympani)
### 2 artifacts:
- sensor lost: flat electrode
- compressed sensor: cardiac pulse dominance

### Tasks
- [x] have list of edf files with signals middle ear @RobinGuillard https://github.com/lkorczowski/Tinnitus-n-Sleep/issues/44#issuecomment-619996418
- [x] qualify signals properties (amplitude range, timing, etc.)
- [x] AmplitudeThresholding + is_good() (detect and remove artifacts)
- [ ] iterate with better algorithm
- [x] visual validation
- [ ] validation of sleep phase

End of sprint Friday 1rd of May at 14:00

## Backlog
- [ ] get labeled bruxism data from expert @RobinGuillard 
- [x] compare masking volume data with episodes @RobinGuillard 
- [x] compare EVA data with episodes @RobinGuillard 
- [ ] #21 Detect bruxism events with noise
- [ ] #24 Detect awake moments 
- [ ] #25 API consistency: `duration`, `interval` and other time-related parameters
- [ ] #26 Benchmarking methods: data simulation
- [ ] #29 Patient selection consensus
- [ ] #30 Are healthy subject of any interest for bruxism analysis?
- [ ] #31 Interesting notes on tinnitus variation
- [ ] #37 Unconsistent number of epoch. see issue for investigation protocol
- [ ] #41 Merging Impedance_thresholding_sliding and AmplitudeThresholding
- [ ] detection of OMA (with accelerometer channel "activity" + artefacts on EOG)
- [x] #45 ind_pick_channels 
- [x] #47 case insensitive hell
- [ ] #49 channels bruxism
- [ ] #51 Add ratio of power
- [ ] #54 invalid channels in valid_chans*.pk
- [ ] #55 slow reporting function

**Comment by RobinGuillard** [comment]
Here is the complete list of nights that are containing middle ear recordings:

1DA15_nuit_hab.edf
1RA17_nuit_hab.edf
1GB18_nuit_son.edf
1MF19_nuit_hab.edf
HZB_nuit_1.edf
HZB_nuit_2.edf
HZB_nuit_3.edf
SCHMIDTLIN_nuit_1_dec_OD__0to0.edf
SCHMIDTLIN_nuit_3_dec_OD__4to0to2.edf
SCHMIDTLIN_nuit_4_dec_OD__3to3.edf
SCHMIDTLIN_nuit_5_dec_OD__0to1.edf
SCHM_nuit_1.edf
SCHM_nuit_2.edf
SCHM_nuit_3.edf
Schmidtlin_nuit_2_dec_3to0to4.edf
Unger_2.edf
unger_nuit_1.edf
Sophie_mema.edf
tom_mema.edf
jon_mema.edf
jose_mema.edf
robin_mema_nuit_1.edf
robin_mema_nuit_2.edf

**Comment by RobinGuillard** [comment]
The paper about Middle Ear Muscle Activity (MEMA) is:
Spontaneous Middle Ear Muscle Activity in Man: A Rapid Eye Movement Sleep Phenomenon
Author(s): Michael A. Pessah and Howard P. Roffwarg
Source: Science, New Series, Vol. 178, No. 4062 (Nov. 17, 1972), pp. 773-776
Published by: American Association for the Advancement of Science
Stable URL: http://www.jstor.org/stable/1735855
It has been added to the file "Resources"

**Comment by lkorczowski** [comment]
Review of the sprint:
- classification of the 3 types of MEMA events is not that easy
- counting the number of MEMA episodes (all types) seems to be positively correlated with tinnitus modulation (EVA p<0,05 for many thresholding, masking volume p<0,05 for fewer).
- inter-subject is validated but more work is required:
    * instead of separating all 3 MEMA, we should at least focus independent of spasmodic
    * several patients should be removed because of very poor night
    * for one given subject, we can predict EVA questionnaire based on MEMA activity (across 7 nights) we should investigate that for other patients
    * even high amplitude thresholds are correlated, i.e. maybe spasmodic ? We should investigate.
- Bruxism_and_MEMA_combine.ipynb combines MEMA and bruxism in three categories: Pure MEMA, Pure Bruxism, Mixed. 
- Even with low amplitude thresholding, adaptive algorithm may not detect all epsiode, we should investigate
- We should investigate forward-backward amplitude thresholding for bruxism
