### ISSUE TITLE
Sprint 6

### ISSUE THREAD

**Issue by lkorczowski** [lkorczowski/Tinnitus-n-Sleep#57]
# SPRINT 6 2020w19(+w20)
_Save final features of both MEMA, Bruxism and Combined (MEMA+Bruxism) and make it ready for results analysis_

## Tasks
- [x] use of the channel "activity" (for OMA, accelerometer on torso) for artifact detection and we should remove all MEMA and bruxism corresponding to movement by refactoring preprocess @RobinGuillard (merge function, #68 ) @lkorczowski (refactoring, #67 )
- [x] add to generate_MEMA_report #51 power ratio for MEMA @lkorczowski , done by PR #60 
- [ ] identify specifically spasmodic MEMA and add info to report
- [ ] add combined pure and mixed events by reading two .pk files from the two inter-subjects NB (bruxism and MEMA)
- [ ] investigate and fix inconsistency of number of epochs, also with sleep stage , see #37 
- [x] change sfreq to 250 Hz everywhere and compare NB output with master @lkorczowski, done by PR #61 
- [x] deal with the interpolation issue #78 , solved by #82 
- [x] refactoring of NBs to integrate the new version of preprocessing, as well as OMA rejection, solved by #82

## Validation
- [ ] visual inspection of accelerometer: movement are removed and combined activity (MEMA or bruxism + movement) are also removed. Benchmark: 3 clean recordings + 2 noisy recordings. Pass mark: at least 3 satisfactory recording. Noisy Recordings: 1BA07, HZBnuit2. Clean Recordings: ....
- [x] Power Ratio for MEMA : pytest
    * INPUT: 2D features (n_epochs, n_electrodes)
    * OUTPUT: 1D features (n_electrodes) Mean Power Ratio per electrode
    * assert 1D with constant power, ratio of power == 1
    * assert n-D with constant power, ratio of power == array of 1
    * assert n-D with change epoch power, ratio of power == new_ratio
- [ ] spasmodic events. Benchmark: confusion matrix on 5 recordings (SCHM, 1RA17, HZBnuit2, TOM, JOHN). Pass mark: max 20% of error.
- [x] pytest for combined MEMA + Bruxism
- [x] compare NB pval between 200 Hz and 250 Hz

**Comment by lkorczowski** [comment]
Sprint review done. Unfinished tasks has been updated and added to Sprint 7 backlog #83
