### ISSUE TITLE
Sprint 7

### ISSUE THREAD

**Issue by lkorczowski** [lkorczowski/Tinnitus-n-Sleep#83]
# Sprint 7 2020w21
_get the final results (but missing sleep staging)_

- [x] starting report with bibliography (.pptx)
- [x] interpolation and preprocess: code review and validation #82 
- [x] refactor normal NB for visualization of annotations. Closed by #85 
- [x] dealing with different sfreq #84 . Closed by #85 
- [x] validation of OMA (with relative threshold of 3) #85 
- [x] refactor NB combined for reading .pk. Closed by #85 
- [x] expand NB combined @RobinGuillard 
- [ ] sleep staging: investigate and fix inconsistency of number of epochs, see #37 (INVALID labels when missing label, detect first and last sleep stage timestamp, cropping raw with sleep stage). Validation1: unitest max 1sec of difference between episodes labels and sleep stage. Validation2: visual validation of sleep annotation on EEG (use another NB).
- [x] Detect when subject is awake and merge with `valid_labels`, crop and rerun NB. Closes #24 
- [ ] statistical analysis between sleep stage and events: add `Nb of episodes per hour per stage of sleep`
- [ ] add detection spasmodic MEMA to the results analysis with `Nb of episodes per hour` and `Nb of episodes per hour per stage of sleep`

**Comment by lkorczowski** [comment]
adding #84
