### ISSUE TITLE
Sprint 8

### ISSUE THREAD

**Issue by lkorczowski** [lkorczowski/Tinnitus-n-Sleep#93]
MORE urgent (update Thursday):
- [x] make csv with include tag (File, subject, session, MEMA, Bruxism, description), see #95 
- [x] refactor Inter-Subject NB standardized functions & pytest & rename figures, see #95 

(initial)
- [ ] change license
- [ ] ECG events (R)
- [ ] local minimum for respiratory signals (e.g. envelope of Hilbert)
- [ ] phase-lock response of MEMA according to ECG and respiratory signals
- [ ] sort MEMA response according to the ECG or respiratory signal frequency
